baseurl: /
languageCode: en-us
title: PhD's, Blogs and Dogs 🐶
theme: "hugo-coder"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 10
    - name: GitHub
      url: https://github.com/lbitchell
      weight: 40
    - name: Twitter
      url: https://twitter.com/BitchellLeah
      weight: 30
    - name: Posts
      url: /post/
      weight: 20
params:
  author: "Leah Bitchell"
  info: "Ph.D Student"
  keywords: "phd, blog, dogs"
  avatarurl: "images/pic.JPG"
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml 
  social: 
    - name: Twitter
      icon: "fa fa-twitter fa-2x"
      url: "https://twitter.com/BitchellLeah"
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  googleTagManager:
    id: "G-QVDM0FZ4JW"
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
